### ISSUE TITLE
Latest version of Excel File - Get error message

### ISSUE THREAD

**Issue by MikeWills** [x2rider/OMISS-Awards#10]
I get the following error: 

Microsoft Excel cannot access the file 'https://d.docs.live.net/Users/Paul/Google Drive/Ham Radio/Omiss/WO4L/OMISS-Awards-WO4L.xlsm'. There are several possible reasons:

• The file name or path does not exist.
• The file is being used by another program.
• The workbook you are trying to save has the same name as a currently open workbook.

**Comment by x2rider** [comment]
I had someone else have this happen, and I’m not sure how this is
happening.  For some reason the file path is a url.  The file needs to be
opened from the local computer.  Where is the file your trying to open?
Try downloading the adi file to your downloads folder or some place local.

**Comment by x2rider** [comment]
I looked at your email again.  There was a version that referenced a
different file, but the latest version doesn't appear to have that since I
removed it.  Are you having this issue with the latest version?

**Comment by MikeWills** [comment]
I downloaded it yesterday. I opened it up on Mac Office 365 on OneDrive. Looks like there is a reference to WO4L's spreadsheet for some reason. IDK. I checked and it happened today. I'll see if I can dig and find it.

**Comment by x2rider** [comment]
Found and removed it.  Grab latest, should be fine now.

**Comment by MikeWills** [comment]
Yep, I wasn't prompted anymore. Thanks. It's a great spreadsheet. I just need to figure out what I qualify for and turn in for some awards.
