### ISSUE TITLE
Dates and Times not showing correctly

### ISSUE THREAD

**Issue by MikeWills** [x2rider/OMISS-Awards#11]
Tabs that I have found the issue: 
* Statehood
* Nealis

Not the end of the world, but thought I'd pass it along when the next update comes. 

<img width="569" alt="Screen Shot 2022-03-08 at 11 01 07 PM" src="https://user-images.githubusercontent.com/139305/157376303-0cf5cbf4-a2fe-4e57-b8af-1c4ec690dc15.png">

**Comment by x2rider** [comment]
Pull latest Excel version, should be updated. #
