### ISSUE TITLE
State Flag Calculating Incorrectly

### ISSUE THREAD

**Issue by MikeWills** [x2rider/OMISS-Awards#12]
In this case, I might be confused, but it's my understanding that the state flag is working 5 unique members by state, but I am getting duplicates in several states, you can see that in the screenshot. Maybe, I'm misunderstanding the rules, but I wanted to make sure that isn't a bug. 

I'm looking at this "1. Contact 5 different amateurs in each of the 48 continental US States, whether the amateurs are mobile, portable or fixed."

![Screen Shot 2022-03-09 at 9 12 15 PM](https://user-images.githubusercontent.com/139305/157581429-ee7d26ae-7633-490c-906c-30dba1c64e9a.png)

**Comment by x2rider** [comment]
Found the issue, and file updated

**Comment by x2rider** [comment]
Thanks for letting me know.  I’ll take a look at it.  I can probably figure
it out, but is this excel or OpenOffice version?

**Comment by MikeWills** [comment]
I use Excel but I thought this was fixed.
