### ISSUE TITLE
Error processing all awards

### ISSUE THREAD

**Issue by MikeWills** [x2rider/OMISS-Awards#13]
I am getting an error running the awards on the new version. I am attaching my adi file and a screenshot of the debugger. I am wondering if it's better if you use the power field rather than try to parse the text field, you might have better luck. Then it's on the person to log their power.
[netlogger.txt](https://github.com/x2rider/OMISS-Awards/files/8648868/netlogger.txt) Rename to adi
<img width="945" alt="Screen Shot 2022-05-08 at 11 56 37 PM" src="https://user-images.githubusercontent.com/139305/167344121-4ff862a1-6c04-48aa-b912-d1a68ce50bfc.png">

**Comment by x2rider** [comment]
Can you change QRP/10 to QRP10?

**Comment by MikeWills** [comment]
It's still breaking there. "NEW QRP10 12823/13690"

Isn't the QRP WAS for when you are operating QRP, not when you work QRP stations? What you are reading would be if the station worked is QRP. 

The rules are "Work stations in all 50 states of the USA QRP using 10 watts of power or less." Unless I'm confused.

**Comment by x2rider** [comment]
Ah, you are correct.  I'll remove that sheet for now, maybe it's one that could be requested, although a tough one to accomplish.

The power routine is still needed for QRP endorsements on other awards, so if you still have issues there, I'll need to know the format of the string it's trying to parse.

**Comment by MikeWills** [comment]
Yeah string parsing is hard especially when the input has no control or consistency. I thought I'd share that before too many people report issues.

**Comment by x2rider** [comment]
Looks like the issue is the new members member numbers being on the same line.

**Comment by x2rider** [comment]
I think I have the parser working for this type of string Mike, please try the latest.

**Comment by MikeWills** [comment]
I think it's working now. No errors after the latest update. Thanks!
