### ISSUE TITLE
City and Address imported incorrectly

### ISSUE THREAD

**Issue by MundaneTracing** [x2rider/OMISS-Awards#14]
City is being populated with Name and address and Address is populated with the City in OM_Ct tab. Don't think it makes a difference in the awards calculation but  noticed tonight as I was about to update the spreadsheet.
![Screen Shot 2022-05-08 at 10 11 32 PM](https://user-images.githubusercontent.com/1944315/167344613-4e467074-c77a-4f33-b14f-ae3479e0823e.png)

**Comment by x2rider** [comment]
Fixed!
