### ISSUE TITLE
Libreoffice 7.x broken

### ISSUE THREAD

**Issue by magpiper** [x2rider/OMISS-Awards#15]
Macros fail to work worked fine under 6.x version. Apologize for the lack of technical details.

**Comment by x2rider** [comment]
I've never used 6.x, all development has been done using 7.x.  I would check your security settings to make sure the scripts are enabled.

**Comment by x2rider** [comment]
Check the security section of the video here: https://www.youtube.com/watch?v=EBXyA3ZQAcg&t=1051s

**Comment by magpiper** [comment]
Tools, options, security - Adjust Macro Security to MEDIUM

![image](https://user-images.githubusercontent.com/4978950/210287699-c737397c-e117-44e3-a9df-d0e67347f065.png)

**Comment by x2rider** [comment]
Ok, that should be fine.
In windows explorer right click on the file, select Properties.
Does it show this?  If so, check the box where it says Unblock and click OK.
![image](https://user-images.githubusercontent.com/2914558/210290257-139446e4-ad44-40df-a1c5-442cd7f32680.png)

also...
When you open the file, does it ask you to Enable Macros, 
![image](https://user-images.githubusercontent.com/2914558/210290062-a95502f5-7e42-4aed-b3e1-803d5eff313a.png)

and does it show 
![image](https://user-images.githubusercontent.com/2914558/210290123-df4574af-2bad-4a4d-b06a-ed3695ef622b.png)
with a button to "Allow Updating"?

**Comment by magpiper** [comment]
Only receive the ENABLE MACROS prompt after setting MACRO security to
MEDIUM (which is fine with me).
I do receive the external links MSG but am able allow it after changing
MACRO setting.

I left UNBLOCK unchecked as referenced above. I don't know if Libreoffice
uses that attribute or not.

**Comment by x2rider** [comment]
If you don't unblock it, the script will not run.
