### ISSUE TITLE
Missing YL

### ISSUE THREAD

**Issue by scotthibbs** [x2rider/OMISS-Awards#7]
I didn't see Linda, N3LY, OMISS # 10758 on the YL list for the Princess Award.
Great Idea, I just submitted for Kings and Queens and District which I didn't know existed until this spreadsheet.
Thanks!
Scott
KD4SIR

**Comment by x2rider** [comment]
Thanks Scott,  I guess you mean the OpenOffice sheet, as I did see her on the Excel sheet.  Unfortunately, we don't have YL in the member feed, so they all have to be added manually.

I've updated the YL list on the OO spreadsheet.
