### ISSUE TITLE
Can't import on Mac Excel 365

### ISSUE THREAD

**Issue by MikeWills** [x2rider/OMISS-Awards#8]
I know we talked last night. I think the issue is that the Mac version of the app treats the files stored in OneDrive folders as URLs, not file paths. I'll do some research on this side, but I'm guessing either I can't store the files in one drive, or there is an option to fix that and I have to research it. Moving to the normal file system allowed the sheet to work. I'm reporting it as a bug for now in case you want to try to research. de WX0MIK

**Comment by x2rider** [comment]
@MikeWills can you try the excel file from the Mac-O365 branch and let me know if that works?

**Comment by MikeWills** [comment]
I'm on the struggle bus on this. I'll try to test it next week again.

**Comment by x2rider** [comment]
I've migrated the fix to the main branch.  Please update from there.
Thanks for reporting this!
